spring:
  application:
    name: habit-tracker
  main:
  datasource:
    url: jdbc:postgresql://localhost:5432/habit_tracker
    username: postgres
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
jwt:
  secret: dGhpcy1pcy1hLXNlY3JldC1rZXktd2hpc2gtaXMtbG9uZy1lbm91Z2gtZm9yLWp3dC10ZXN0aW5nLXByb2Nlc3M=